name: build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Simulate Audio Device
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Expand-7ZipArchive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - name: Check Audio Device
        shell: powershell
        run: Get-CimInstance Win32_SoundDevice | fl *
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-portaudio
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: libpazaudio.a
  #macos: # HANGS ON TEST/TEST
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Build and Test
  #      run: make -j
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: macos-build
  #        path: libpazaudio.a
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt install portaudio19-dev
      - name: Simulate Audio Device
        run: |
          sudo apt install pulseaudio
          pulseaudio --start
      - name: Check Audio Device
        run: pactl list short
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: libpazaudio.a
